Fix historical Thanksgivings
wakproductions/stock_market_days pull request #5
Opened 2024-02-25 22:23 UTC by wtn

2024-02-25 22:49 UTC, wakproductions requested changes

2024-02-25 22:49 UTC, wakproductions commented on lib/market_open_days/nyse_market_days.csv
> -2020-11-26
Bruh these dates are correct!
11/28/2019 - SPY closed at 310.27, was closed on the 28th
11/19/2020 - SPY closed at 357.78, was closed on the 26th

![image](https://github.com/wakproductions/stock_market_days/assets/1912237/4e6b8a8e-fcd6-4b0b-95bb-3523dd6ffebd)


![image](https://github.com/wakproductions/stock_market_days/assets/1912237/06c362ad-5852-42d9-b217-94a0011dd6d2)

2024-02-25 23:37 UTC, wtn commented on lib/market_open_days/nyse_market_days.csv
> -2020-11-26
I agree completely that the market was open on the two days you pointed to on the charts. That's why I added them to the "market open days" file and removed the two instances of Thanksgiving Day that should not have been there.

![Thanksgiving](https://github.com/wakproductions/stock_market_days/assets/35801/fad61383-8217-42ea-a3a8-3a1d3daaa5a8)

2024-02-25 23:40 UTC, wakproductions commented on lib/market_open_days/nyse_market_days.csv
> -2020-11-26
oh darn that's totally right! what was I thinking?! thanks so much for your contribution!!! sorry for the misunderstanding.

2024-02-25 23:41 UTC, wakproductions approved these changes

2024-02-25 23:55 UTC, wtn commented
I fixed a few more historical market holidays. Everything from 2016-01-01 to present should be correct now.

[NYSE Group press release for 2016 & 2017 holidays](https://www.businesswire.com/news/home/20160202006502/en/NYSE-Group-Announces-2017-Holiday-and-Early-Closings-Calendar)

2024-02-26 00:06 UTC, wakproductions approved these changes
lgtm! Thanks!

2024-04-20 00:24 UTC, wtn commented
Please merge, thanks.

2024-04-20 02:11 UTC, merged